version: '3'
mariadb:
  image: mariadb:10
  volumes:
    - schema.sql:/docker-entrypoint-initdb.d
  environment:
{{- if eq .Values.mysql_allow_empty_password "yes"}}
    MYSQL_ALLOW_EMPTY_PASSWORD: ${mysql_allow_empty_password}
{{- end}}
{{- if (.Values.mysql_database)}}
    MYSQL_DATABASE: ${mysql_database}
{{- end}}
{{- if (.Values.mysql_password)}}
    MYSQL_PASSWORD: ${mysql_password}
{{- end}}
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
{{- if (.Values.mysql_user)}}
    MYSQL_USER: ${mysql_user}
{{- end}}
